import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/globals.css";
import "@/styles/styles.css";
import "@/styles/queries.css";
import { ToastContainer } from "react-toastify";
import { AppProvider } from "@/context/context";
import Layout from "@/layout/layout.index";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Furr Baby</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppProvider>
        <Layout>
          <ToastContainer />
          <Component {...pageProps} />
        </Layout>
      </AppProvider>
    </>
  );
}
